In [27]:
import pandas as pd
import numpy as np

In [34]:
# add article_list
article_list = pd.read_csv("raw_data/Article_list.csv")
article_list.head(5)

ID paper assigned ID               Type Study Groupings  \
0   1        Hooper2002  Systematic Review             NaN   
1   2        Hooper2003  Systematic Review             NaN   
2   3        Hooper2004  Systematic Review             NaN   
3   4    Strazzullo2009  Systematic Review             NaN   
4   5       Taylor2011a  Systematic Review             NaN   

                                               Title  year      Attitude  \
0  Systematic review of long term effects of advi...  2002  inconclusive   
1  Reduced dietary salt for prevention of cardiov...  2003  inconclusive   
2  Advice to reduce dietary salt for prevention o...  2004  inconclusive   
3  Salt intake, stroke, and cardiovascular diseas...  2009           for   
4  Reduced dietary salt for the prevention of car...  2011  inconclusive   

                              Doi Retracted (Y/N)  
0        10.1136/bmj.325.7365.628             NaN  
1       10.1002/14651858.CD003656             NaN  
2  10.1002/14651858.CD003656.pub2             NaN  
3               10.1136/bmj.b4567             NaN  
4            10.1038/ajh.2011.115             NaN

In [6]:
data = pd.read_csv('raw_data/salt_cont_auth_updated_hyper_tension.csv')

In [7]:
data.head(5)

ID                                     original_title author_given_name  \
0   1  Systematic review of long term effects of advi...               Lee   
1   1  Systematic review of long term effects of advi...       Christopher   
2   1  Systematic review of long term effects of advi...      George Davey   
3   1  Systematic review of long term effects of advi...              Shah   
4   2  Reduced dietary salt for prevention of cardiov...                L.   

  author_surname    author_id organizational_author  manual  
0         Hooper  57202855325                   NaN   False  
1       Bartlett  57194377301                   NaN   False  
2          Smith  35354080500                   NaN   False  
3        Ebrahim   7102093023                   NaN   False  
4         Hooper  57202855325                   NaN   False

In [8]:
data.ID.sort_values().unique() # total number matches

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
       80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93],
      dtype=int64)

In [9]:
len(data.ID.sort_values().unique())

82

In [13]:
data.loc[data['manual']== False ,'ID'].unique()

array([ 1,  2,  3,  4,  5,  7,  9, 12, 13, 26, 27, 30, 31, 33, 34, 38, 39,
       40, 41, 42, 43, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 58, 59, 61,
       62, 63, 64, 65, 66, 67, 68, 70, 71, 73, 74, 75, 76, 77, 78, 79, 80,
       81, 82, 83, 84, 85, 87, 88, 89, 90, 92,  6, 11, 46, 56, 57, 69, 14,
       28, 60, 86, 91, 93], dtype=int64)

In [14]:
len(data.loc[data['manual']== False ,'ID'].unique())

73

In [15]:
len(data.loc[data['manual']== True ,'ID'].unique())

9

In [17]:
data.loc[data['manual']== True ,'ID'].sort_values().unique()

array([ 8, 10, 29, 32, 35, 36, 37, 44, 72], dtype=int64)

Note: Article 8, 10, 29, 32, 35, 36, 37, 44, and 72 are maunally scraped.

In [19]:
output_1 = pd.read_csv("raw_data/output_2022-03-07-16-43-10.csv")
output_1.head(5)

ID                                     original_title  \
0   1  Systematic review of long term effects of advi...   
1   1  Systematic review of long term effects of advi...   
2   1  Systematic review of long term effects of advi...   
3   1  Systematic review of long term effects of advi...   
4   2  Reduced dietary salt for prevention of cardiov...   

                                           scp_title  title_match(true/false)  \
0  Systematic review of long term effects of advi...                     True   
1  Systematic review of long term effects of advi...                     True   
2  Systematic review of long term effects of advi...                     True   
3  Systematic review of long term effects of advi...                     True   
4  Reduced dietary salt for prevention of cardiov...                     True   

  author_given_name author_surname    author_id  
0               Lee         Hooper  57202855325  
1       Christopher       Bartlett  57194377301  
2      George Davey          Smith  35354080500  
3              Shah        Ebrahim   7102093023  
4                L.         Hooper  57202855325

In [21]:
output_1.ID.sort_values().unique()

array([ 1,  2,  3,  4,  5,  6,  7,  9, 11, 12, 13, 26, 27, 28, 30, 31, 33,
       34, 38, 39, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 73,
       74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 87, 88, 89, 90, 92],
      dtype=int64)

In [22]:
len(output_1.ID.sort_values().unique())

68

In [53]:
# prepare the two output for concatenation
output_2 = pd.read_csv("raw_data/output_doi_2022-03-08-09-42-05.csv")
output_2 = article_list[['ID', 'Title']].merge(output_2, on='ID')
output_2.rename(columns={"Title":"title"},inplace=True)
output_2.head(5)
output_2['organizational_author'] = np.nan
output_2['manual'] = False
output_2.head(5)

ID                                              title author_given_name  \
0   6  Reduced dietary salt for the prevention of car...            Rod S.   
1   6  Reduced dietary salt for the prevention of car...           Kate E.   
2   6  Reduced dietary salt for the prevention of car...           Tiffany   
3   6  Reduced dietary salt for the prevention of car...               Lee   
4   6  Reduced dietary salt for the prevention of car...              Shah   

  author_surname    author_id  organizational_author  manual  
0         Taylor  55628530729                    NaN   False  
1         Ashton  26644694600                    NaN   False  
2         Moxham  26657630700                    NaN   False  
3         Hooper  57202855325                    NaN   False  
4        Ebrahim  56500020000                    NaN   False

In [47]:
output_2.ID.sort_values().unique()

array([ 6, 11, 14, 28, 46, 56, 57, 60, 69, 86, 91, 93], dtype=int64)

In [48]:
len(output_2.ID.sort_values().unique())

12

In [112]:
output_1 = pd.read_csv("raw_data/output_2022-03-07-16-43-10.csv")
output_1.drop(columns=["scp_title","title_match(true/false)"], inplace=True)
index_to_remove = output_1.index[output_1.ID.isin(list(output_2.ID.sort_values().unique()))]
output_1.drop(index = index_to_remove, axis=0,inplace=True)
output_1['organizational_author'] = np.nan
output_1['manual'] = False
output_1.rename(columns={"original_title":'title'}, inplace=True)
output_1.head(5)

ID                                              title author_given_name  \
0   1  Systematic review of long term effects of advi...               Lee   
1   1  Systematic review of long term effects of advi...       Christopher   
2   1  Systematic review of long term effects of advi...      George Davey   
3   1  Systematic review of long term effects of advi...              Shah   
4   2  Reduced dietary salt for prevention of cardiov...                L.   

  author_surname    author_id  organizational_author  manual  
0         Hooper  57202855325                    NaN   False  
1       Bartlett  57194377301                    NaN   False  
2          Smith  35354080500                    NaN   False  
3        Ebrahim   7102093023                    NaN   False  
4         Hooper  57202855325                    NaN   False

In [93]:
output_1.ID.sort_values().unique()

array([ 1,  2,  3,  4,  5,  7,  9, 12, 13, 26, 27, 30, 31, 33, 34, 38, 39,
       40, 41, 42, 43, 45, 47, 48, 49, 50, 51, 52, 53, 54, 55, 58, 59, 61,
       62, 63, 64, 65, 66, 67, 68, 70, 71, 73, 74, 75, 76, 77, 78, 79, 80,
       81, 82, 83, 84, 85, 87, 88, 89, 90, 92], dtype=int64)

In [94]:
len(output_1.ID.sort_values().unique())

61

In [113]:
# concatenate two dataframes
final_output = pd.concat([output_1,output_2],axis=0)

In [96]:
final_output.ID.sort_values().unique()

array([ 1,  2,  3,  4,  5,  6,  7,  9, 11, 12, 13, 14, 26, 27, 28, 30, 31,
       33, 34, 38, 39, 40, 41, 42, 43, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
       71, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
       89, 90, 91, 92, 93], dtype=int64)

In [97]:
len(final_output.ID.sort_values().unique())

73

In [98]:
data.loc[data['manual']== True ,'ID'].sort_values().unique()

array([ 8, 10, 29, 32, 35, 36, 37, 44, 72], dtype=int64)

In [99]:
len(data.loc[data['manual']== True ,'ID'].sort_values().unique())

9

In [110]:
# prepare the concatenate the manually retrieved data
manual_data = data[data['manual']].copy()
manual_data.rename(columns={"original_title": "title"},inplace=True)
manual_data.head(4)

ID                                              title author_given_name  \
529   8  Effect of reduced sodium intake on cardiovascu...                 N   
530  10  Low sodium versus normal sodium diets in systo...                JJ   
531  10  Low sodium versus normal sodium diets in systo...                 P   
532  10  Low sodium versus normal sodium diets in systo...                RS   

     author_surname    author_id organizational_author  manual  
529          Aburto   8739842100                   NaN    True  
530  DiNicolantonio            3                   NaN    True  
531      DiPasquale   7006484941                   NaN    True  
532          Taylor  55628530729                   NaN    True

In [104]:
len(manual_data.ID.sort_values().unique())

9

In [114]:
# final concatenation
final_dataframe = pd.concat([final_output,manual_data],axis=0)
final_dataframe.head(5)

ID                                              title author_given_name  \
0   1  Systematic review of long term effects of advi...               Lee   
1   1  Systematic review of long term effects of advi...       Christopher   
2   1  Systematic review of long term effects of advi...      George Davey   
3   1  Systematic review of long term effects of advi...              Shah   
4   2  Reduced dietary salt for prevention of cardiov...                L.   

  author_surname    author_id organizational_author  manual  
0         Hooper  57202855325                   NaN   False  
1       Bartlett  57194377301                   NaN   False  
2          Smith  35354080500                   NaN   False  
3        Ebrahim   7102093023                   NaN   False  
4         Hooper  57202855325                   NaN   False

In [115]:
final_dataframe.ID.sort_values().unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
       80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93],
      dtype=int64)

In [116]:
len(final_dataframe.ID.sort_values().unique())

82

In [118]:
final_dataframe.to_csv("salt_cont_author.csv",index=False, encoding='UTF-8')